### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by obi12341** [SuckerServ/suckerserv#12]
Demo recording is not working. You have to create the directory "demo" in log/ manually to get it working.

**Comment by tpoechtrager** [comment]
Probably the cause of git not supporting directories. Putting a `.keepme` file in `demo/` should fix it.

**Comment by piernov** [comment]
Yep, git doesn't support empty directory whereas subversion does, and SuckerServ doesn't create this dir before trying to write in it.
However the `bin/utils/newserver.sh` script creates the required dir. So maybe better not to add the` log/` dir to git but to create it at runtime.

**Comment by obi12341** [comment]
some are not using bin/utils/newserver.sh so the directory should already be there
