### ISSUE TITLE
There is something wrong with EXT_UPTIME

### ISSUE THREAD

**Issue by tpoechtrager** [SuckerServ/suckerserv#22]
Two distinct `EXT_UPTIME` requests with a time difference of ~5 seconds give me the same uptime value.

Only HopMod and SuckerServ seem to be affected

    error: wrong uptime: suckerserv | SuckerServ-master | uptime: 654402 (expected: ~654407) | empty: yes
    error: wrong uptime: hopmod | CoE II | uptime: 15743741 (expected: ~15743746) | empty: yes
    error: wrong uptime: hopmod | CoE I | uptime: 2783305 (expected: ~2783309) | empty: yes
    error: wrong uptime: hopmod | |noVI: underground | uptime: 261537 (expected: ~261542) | empty: yes
    error: wrong uptime: hopmod | C  A  L  M    P  A  R  K | uptime: 309494 (expected: ~309499) | empty: yes
    error: wrong uptime: suckerserv | Cccc | uptime: 2332540 (expected: ~2332545) | empty: yes
    error: wrong uptime: hopmod | M A P  P A R K | uptime: 5258980 (expected: ~5258985) | empty: yes
    error: wrong uptime: hopmod | (AMARO) | uptime: 974998 (expected: ~975003) | empty: yes
    error: wrong uptime: hopmod | sp4nk GangBang | uptime: 3463283 (expected: ~3463288) | empty: yes
    error: wrong uptime: hopmod | icc gufopowered exp | uptime: 3462343 (expected: ~3462348) | empty: yes
    error: wrong uptime: suckerserv | South Africa v5 | uptime: 1791731 (expected: ~1791735) | empty: yes
    error: wrong uptime: suckerserv | |AoG| Training Field | uptime: 1642572 (expected: ~1642577) | empty: yes
    error: wrong uptime: suckerserv | |AoG| Mapping Zone | uptime: 1648732 (expected: ~1648737) | empty: yes
    error: wrong uptime: suckerserv | 2FY BlackJack Table | uptime: 1659234 (expected: ~1659239) | empty: yes
    error: wrong uptime: suckerserv | HELLOSERV | uptime: 130269 (expected: ~130274) | empty: yes
    error: wrong uptime: suckerserv | H I D E  &  S E E K | uptime: 1491851 (expected: ~1491856) | empty: yes
    error: wrong uptime: suckerserv | |AoG| Clan Server | uptime: 1641923 (expected: ~1641928) | empty: yes
    error: wrong uptime: suckerserv | |AoG| Insta CTF | uptime: 1629204 (expected: ~1629209) | empty: yes
    error: wrong uptime: suckerserv | 2FY Poker Table | uptime: 1638996 (expected: ~1639000) | empty: yes

**Comment by piernov** [comment]
I think that time isn't updated when the server is empty. `update_time()` is the function handling it (in `engine/server.cpp`). It's called in `update_server()`  which doesn't schedule the next update if there are no clients connected:

    void update_server(const std::error_code & error = std::error_code())
    {
        if(nonlocalclients > 0) sched_next_update();
    
        update_time();
    }

Maybe uptime should have it's own timer ran every seconds?

**Comment by tpoechtrager** [comment]
You could initialize a variable with [getnanoseconds()](https://github.com/SuckerServ/suckerserv/search?utf8=%E2%9C%93&q=getnanoseconds) on startup - then just do `putint(p, getnanoseconds() - start) / 1000000000ULL`.

**Comment by piernov** [comment]
This would work but since the `totalsecs` variable is especially here for the uptime, shouldn't we update it instead ? If we use `server.uptime` in a Lua script when no one is connected, this information is wrong. Let's say I add an `UPTIME` field to the output of `./bin/server status`. If no one connects to the server, it'll always be 0.

**Comment by tpoechtrager** [comment]
`totalsecs` is a (very) stupid hack to avoid 32-bit integer overflows, my solution is the proper way...

**Comment by piernov** [comment]
So adding a function like `int getuptime() { return (getnanoseconds()-startup)/1000000000ULL; }` instead of `totalsecs` would be ok ? (binded as a prop with a getter to replace `server.uptime` in Lua)

**Comment by tpoechtrager** [comment]
Yes, should work.

**Comment by piernov** [comment]
Thanks a lot, I hope I fixed it right.
